### ISSUE TITLE
White Screen on Windows 11

### ISSUE THREAD

**Issue by yarg-eth** [ethereum/remix-desktop#119] opened 2022-04-14 23:07 UTC
Launches a white screen. Cannot open any folders or do anything else. Please work on this issue. I have seen another issue that is the same, but no one has helped so I am bringing it back up.

**Comment by saqoah** [comment] 2022-04-15 02:25
i got same issue when uninstalled github desktop and pycharm, lost all my contracts sources, but im still trying i will update my answer when i fix it.

**Comment by driver4567** [comment] 2022-04-15 05:24
same

**Comment by ZawadiMan** [comment] 2022-04-15 10:40
Same on Windows 10 1:st installation

**Comment by screencredits** [comment] 2022-04-15 14:01
Remix-Project deployed a new release yesterday (v0.23.0.). I believe the problem is being caused by the changes, more specifically: https://github.com/ethereum/remix-project/pull/2274

**Comment by yarg-eth** [comment] 2022-04-15 16:28
I'll let you know if it works. The problem is that the previous release was not working either.

**Comment by saqoah** [comment] 2022-04-16 21:49
```
fetch('https://remix.ethereum.org/assets/version.json', { cache: "no-store" }).then(response => {
  response.text().then(function (data) {
    const version = JSON.parse(data);
    console.log(`Loading Remix ${version.version}`);
    createScriptTag(`polyfills.${version.version}.${version.timestamp}.js`, 'module');
    if (version.mode === 'development') {
      createScriptTag(`vendor.${version.version}.${version.timestamp}.js`, 'module');
      createScriptTag(`runtime.${version.version}.${version.timestamp}.js`, 'module');
    }
    createScriptTag(`main.${version.version}.${version.timestamp}.js`, 'text/javascript');
  });
});
```

press CTRL+SHIFT+I to open console
Just past this in the console

**Comment by yarg-eth** [comment] 2022-04-17 02:21
@saqoah This worked, but I am leaving this issue open as this is something that their developers need to fix. Thanks a lot. I also see some more errors after running this in the console, do not know if this will be problematic, but I will report any errors that I run into while working in this thread.

**Comment by ZawadiMan** [comment] 2022-04-17 19:07
Yes it worked, but as said, there where some error messages.
After closing it and trying to reopen i get:

loader.js:28 Fetch API cannot load package://6fd22d6fe5549ad4c4d8fd3ca0b7816b.mod/assets/version.json. URL scheme "package" is not supported.
Uncaught (in promise) TypeError: Failed to fetch
    at loader.js:28

and the workspace is white again, i have to re-run the fix to get the workspace view (perhaps i dont understand how this is supposed to work).

**Comment by yann300** [comment] 2022-09-09 12:39
the latest release should fix that - https://github.com/ethereum/remix-desktop/releases - sorry for the delay.
Please make sure to reopen if the issue persists.

**Closed by yann300** 2022-09-09 12:39 UTC

**Comment by temuera** [comment] 2022-11-27 20:46
1.35 + remix 2.81 white same pb.
